# Generated by Django 3.1.4 on 2020-12-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleDistribution', models.CharField(max_length=70, verbose_name='Titulo de Distribucion')),
                ('titleOriginal', models.CharField(max_length=70, verbose_name='Titulo Original')),
                ('gender', models.CharField(max_length=30, verbose_name='Genero')),
                ('languaje', models.CharField(max_length=30, verbose_name='Idioma')),
                ('yearProducction', models.CharField(max_length=4, verbose_name='Año de Produccion')),
                ('web', models.CharField(max_length=100, verbose_name='Direccion web')),
                ('duration', models.TimeField(verbose_name='Duracion')),
                ('score', models.CharField(max_length=10, verbose_name='Calificacion')),
                ('premiereDate', models.DateField(verbose_name='Premier')),
                ('description', models.CharField(max_length=600, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
            },
        ),
    ]
