# Generated by Django 3.1.4 on 2020-12-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languajeSubtitle', models.CharField(max_length=30, verbose_name='Idioma del subtitulo')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Pelicula')),
            ],
            options={
                'verbose_name': 'Datos del Reparto',
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('nationality', models.CharField(max_length=30, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Datos del Reparto',
            },
        ),
        migrations.CreateModel(
            name='DistributionMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='Rol')),
                ('distributionData_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.distributiondata', verbose_name='Nombre del reparto')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Pelicula')),
            ],
            options={
                'verbose_name': 'Pelicula del Reparto',
            },
        ),
    ]
