# Generated by Django 3.1.4 on 2020-12-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_distributiondata_distributionmovie_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributionmovie',
            options={'verbose_name': 'Repardo por Pelicula'},
        ),
    ]
