# Generated by Django 3.1.4 on 2020-12-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201204_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Cine')),
                ('address', models.CharField(max_length=300, verbose_name='Direccion')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Cine',
                'verbose_name_plural': 'Cines',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Sala')),
                ('number', models.IntegerField(verbose_name='Numero')),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.AlterModelOptions(
            name='distributionmovie',
            options={'verbose_name': 'Reparo por Pelicula'},
        ),
    ]
