# Generated by Django 3.1.4 on 2020-12-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201205_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Duracion')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Pelicula')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.room', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciomes',
            },
        ),
        migrations.AlterModelOptions(
            name='distributionmovie',
            options={'verbose_name': 'Reparto por Pelicula'},
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('age', models.CharField(max_length=2, verbose_name='Edad')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('score', models.CharField(max_length=10, verbose_name='puntuacion')),
                ('commentary', models.CharField(max_length=500, verbose_name='Comentario')),
                ('function_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.function', verbose_name='Funcion')),
            ],
            options={
                'verbose_name': 'Opinion',
                'verbose_name_plural': 'Opiniones',
            },
        ),
    ]
