# Generated by Django 3.1.4 on 2020-12-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201205_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opinion',
            new_name='Commentary',
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'Funcion', 'verbose_name_plural': 'Funciones'},
        ),
    ]
